version: '3.7'

services:
    attbot:
        build:
            context: .
            dockerfile: Dockerfile
        image: steve_imm/attbot
        container_name: attbot
        restart: unless-stopped
        env_file: .env
        environment:
            - WAIT_HOSTS=$DB_HOST:3306
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=15
            - WAIT_HOST_CONNECT_TIMEOUT=30
        links: 
            - attbot_db
        depends_on: 
            - attbot_db
        command: sh -c "/wait && gunicorn --certfile=cert/webhook_cert.pem --keyfile=cert/webhook_pkey.pem --bind $WEBHOOK_LISTEN:$WEBHOOK_PORT attbot:app --timeout 90"
        ports: 
            - 8443:8443
  
    attbot_db:
        image: mysql
        container_name: attbot_db
        restart: always
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: $DB_PASSWORD
            MYSQL_DATABASE: $DB_NAME
            TZ: $TZ
        volumes:
            - ./db:/docker-entrypoint-initdb.d
        command: --default-authentication-plugin=mysql_native_password